function graph_AEXP(X1, YMatrix1)
%CREATEFIGURE(X1,YMATRIX1)
%  X1:  vector of x data
%  YMATRIX1:  matrix of y data

%  Auto-generated by MATLAB on 19-Jun-2012 16:28:08

% Create figure
figure1 = figure('Color',...
    [0.800000011920929 0.800000011920929 0.800000011920929]);

% Create axes
axes1 = axes('Parent',figure1,'YMinorTick','on','XMinorTick','on',...
    'FontWeight','bold');
hold(axes1,'all');

% Create multiple lines using matrix input to plot
plot1 = plot(X1,YMatrix1,'Parent',axes1,'LineWidth',2);
set(plot1(1),'Color',[0 0.498039215803146 0],'DisplayName','Hot-spot');
set(plot1(2),'Color',[0 0 1],'DisplayName','Top-oil');

% Create xlabel
xlabel('Time [min]','FontWeight','bold');

% Create ylabel
ylabel('Temperature [C]','FontWeight','bold');

% Create title
title('Cyclic Loading - Load Stepped','FontWeight','bold','FontSize',12);

% Create legend
legend1 = legend(axes1,'show');
set(legend1,'EdgeColor',[1 1 1],'Location','Best','YColor',[1 1 1],...
    'XColor',[1 1 1],...
    'FontAngle','italic');

